In [1]:
import pandas as pd
import numpy as np

In [2]:
arr1d = np.array([1,2,3])
print(arr1d)

[1 2 3]


In [3]:
print(arr1d[1])

2


In [4]:
arr2d = np.array([[1,2,3], [4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [5]:
print(arr2d[1][0])

4


In [13]:
arr3d = np.array([[[1,2,3],[4,5.0,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [14]:
print(arr3d[0][1][2])

6.0


### Attributes of Numpy Array:
 1. size = tells us the total number of elements in the array.
 2. shape =gives us the size of each dimension.
 3. dtype = tells us the data type of the elements in the array.
 4. ndim = tells us the number of dimensions of the array.

In [15]:
print(arr3d.size)

12


In [16]:
print(arr3d.shape)

(2, 2, 3)


In [17]:
print(arr2d.shape)

(2, 3)


In [18]:
print(arr1d.shape)

(3,)


In [19]:
print(arr3d.dtype)

float64


In [21]:
print(arr3d.ndim)

3


### Adding Arrays vs Numpy Arrays

In [23]:
arr1 = [1,2,3]
arr2 = [4,5,6]

res = arr1 + arr2
print(res)

[1, 2, 3, 4, 5, 6]


In [40]:
arr1d = np.array([1,2,3])
arr1d2 = np.array([4,5,6])

res = arr1d + arr1d2
# res = arr1d - arr1d2
# res = arr1d * arr1d2
# res = arr1d / arr1d2
print(res)

[5 7 9]


### Indexing, Splicing, Reshaping

In [28]:
print(arr2d[0,2])

3


In [29]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [37]:
print(arr2d[1:2:1])

[[4 5 6]]


In [39]:
print(arr2d.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]
